name: Test
on:
  workflow_dispatch:

jobs:
  Test:
    name: Test
    runs-on: windows-latest
    steps:
    - run: 
      shell:
    - run: Get-ChildItem -Path "C:\Program Files (x86)"
      shell: pwsh

    - run: Get-ChildItem -Path "C:\Program Files (x86)\Microsoft Visual Studio"
      shell: pwsh

    - run: Get-ChildItem -Path "C:\Program Files (x86)\Microsoft Visual Studio\Installer"
      shell: pwsh