name: Test
on:
  push:
  workflow_dispatch:

jobs:
  Test:
    name: Test
    runs-on: windows-latest
    steps:
    - run: |
        If ($IsWindows) {
          Write-Host "Win"
        } else {
          Write-Host "Ubuntu"
        }
      shell: pwsh